### ISSUE TITLE
Implement dynamic colours. (Material You)

### ISSUE THREAD

**Issue by ghost** [jplie/Moegram-X#20]
This telegram client is really good, but one thing that's missing is Material You. I've seen it on other telegram clients such as MDgram, Nekogram, etc. And would love to see this on this client :)

**Comment by RezurrectBodg** [comment]
you could use and improve upon the half-baked @itaysonlab code:
https://github.com/iTaysonLab/TgxDynamics

**Comment by iTaysonLab** [comment]
> you could use and improve upon the half-baked @itaysonlab code:
> https://github.com/iTaysonLab/TgxDynamics

😭

there is a 146% chance of adding new variables through this years, so good luck

also - color matching code is very old and uses legacy system APIs - you might be better using official Google libraries instead (or materialkolor)
