### ISSUE TITLE
make a special build version of MGX

### ISSUE THREAD

**Issue by DI555** [jplie/Moegram-X#29]
@jplie , since no sms to phone, and it is obviously a rudeness((, could you please making also and builds by a telegraher way, - using the official keys and some telegraher’s patches/commits ???

**Comment by jplie** [comment]
Neither method such as use of vanilla keys can't bring back SMS and email codes sending because of another telegram checks that cannot be bypassed.

**Comment by DI555** [comment]
- yep, it’s f..ing firebase check((, but..(!)..there’s two, even three, hints!
1. its doesn’t switch on by default, if no gp installed, - it’s off!
2. and  there must be phone name spoof option, to tell that it’s huawei model, so - this chek will be switch off by now!
3. root plus spoof fb check module will solve that problem, ..on medium chek for now.

**Comment by jplie** [comment]
Yep, it sounds not too complicated, but anyway do such work for the thing, that you will use only one time to login too wasteful. And anyway you can install vanilla tg to login for the only one time.  I can add it todo, but I have a lot of things that will be used a lot frequently and need to be implemented too.

**Comment by nubesurrealista** [comment]
@jplie We love u Kirao, relax and calm down

**Comment by jplie** [comment]
@dskzero22 Why it always add my tag, that also sends me push from GitHub
